exports.MOWER_RAW_MQTT = {
    "mower_raw.consumable_items": {
        en: "Consumable items",
        de: "Verbrauchsmaterialien",
        ru: "Расходные материалы",
        pt: "Itens consumíveis",
        nl: "Verbruiksartikelen",
        fr: "Articles consommables",
        it: "Articoli di consumo",
        es: "Artículos consumibles",
        pl: "Przedmioty eksploatacyjne",
        uk: "Витратні матеріали",
        "zh-cn": "消耗品",
    },
    "mower_raw.blade": {
        en: "Blade info",
        de: "Klingeninformationen",
        ru: "Информация о лезвии",
        pt: "Informações sobre a lâmina",
        nl: "Informatie over het mes",
        fr: "Informations sur la lame",
        it: "Informazioni sulla lama",
        es: "Información de la hoja",
        pl: "Informacje o ostrzu",
        uk: "Інформація про лезо",
        "zh-cn": "刀片信息",
    },
    "mower_raw.charge_pos": {
        en: "Charger device position",
        de: "Position des Ladegeräts",
        ru: "Положение зарядного устройства",
        pt: "Posição do dispositivo de carregamento",
        nl: "Positie van het laadapparaat",
        fr: "position du chargeur",
        it: "Posizione del dispositivo di ricarica",
        es: "Posición del dispositivo de carga",
        pl: "Pozycja urządzenia ładującego",
        uk: "Положення зарядного пристрою",
        "zh-cn": "充电器设备位置",
    },
    "mower_raw.consumable_items.blade": {
        en: "Blade info",
        de: "Klingeninformationen",
        ru: "Информация о лезвии",
        pt: "Informações sobre a lâmina",
        nl: "Informatie over het mes",
        fr: "Informations sur la lame",
        it: "Informazioni sulla lama",
        es: "Información de la hoja",
        pl: "Informacje o ostrzu",
        uk: "Інформація про лезо",
        "zh-cn": "刀片信息",
    },
    "mower_raw.consumable_items.cutter": {
        en: "Mow cutter info",
        de: "Informationen zum Mähwerk",
        ru: "Информация о косилке",
        pt: "Informações sobre cortadores de grama",
        nl: "Informatie over grasmaaiers",
        fr: "Informations sur la tondeuse",
        it: "Informazioni sul tagliaerba",
        es: "Información sobre cortadoras de césped",
        pl: "Informacje o kosiarce",
        uk: "Інформація про косильну машину",
        "zh-cn": "割草机信息",
    },
    "mower_raw.file_17": {
        en: "Path-file uploaded",
        de: "Pfaddatei hochgeladen",
        ru: "Путь к загруженному файлу",
        pt: "Arquivo de caminho carregado",
        nl: "Padbestand geüpload",
        fr: "Fichier de chemin téléchargé",
        it: "Percorso del file caricato",
        es: "Ruta del archivo cargado",
        pl: "Plik ścieżki przesłany",
        uk: "Завантажений файл шляху",
        "zh-cn": "上传路径文件",
    },
    "mower_raw.file_7": {
        en: "Map-file uploaded",
        de: "Kartendatei hochgeladen",
        ru: "Файл карты загружен",
        pt: "Arquivo de mapa carregado",
        nl: "Kaartbestand geüpload",
        fr: "Fichier de carte téléchargé",
        it: "File della mappa caricato",
        es: "Archivo de mapa subido",
        pl: "Plik mapy przesłany",
        uk: "Завантажено файл карти",
        "zh-cn": "地图文件已上传",
    },
    "mower_raw.mow_efficiency": {
        en: "Mow efficiency",
        de: "Mähleistung",
        ru: "Эффективность кошения",
        pt: "Eficiência de corte",
        nl: "Maai-efficiëntie",
        fr: "efficacité de tonte",
        it: "Efficienza di falciatura",
        es: "eficiencia del corte",
        pl: "Efektywność koszenia",
        uk: "Ефективність скошування",
        "zh-cn": "割草效率",
    },
    "mower_raw.notice": {
        en: "Message",
        de: "Nachricht",
        ru: "Сообщение",
        pt: "Mensagem",
        nl: "Bericht",
        fr: "Message",
        it: "Messaggio",
        es: "Mensaje",
        pl: "Wiadomość",
        uk: "Повідомлення",
        "zh-cn": "信息",
    },
    "mower_raw.rain": {
        en: "Rain settings",
        de: "Regeneinstellungen",
        ru: "настройки дождя",
        pt: "Configurações de chuva",
        nl: "Regeninstellingen",
        fr: "Paramètres de pluie",
        it: "Impostazioni pioggia",
        es: "Configuración de lluvia",
        pl: "Ustawienia deszczu",
        uk: "Налаштування для дощу",
        "zh-cn": "雨景",
    },
    "mower_raw.robot_pos": {
        en: "Mower position",
        de: "Mäherposition",
        ru: "положение газонокосилки",
        pt: "Posição do cortador de grama",
        nl: "Maaipositie",
        fr: "Position de la tondeuse",
        it: "Posizione del tosaerba",
        es: "Posición de la segadora",
        pl: "Pozycja kosiarki",
        uk: "Положення косарки",
        "zh-cn": "割草机位置",
    },
    "mower_raw.rtk_pos": {
        en: "RTK position",
        de: "RTK-Position",
        ru: "Позиция RTK",
        pt: "Posição RTK",
        nl: "RTK-positie",
        fr: "Position RTK",
        it: "Posizione RTK",
        es: "Posición RTK",
        pl: "Pozycja RTK",
        uk: "Позиція RTK",
        "zh-cn": "RTK位置",
    },
    "mower_raw.schedule_info": {
        en: "Last/actual schedule infos",
        de: "Letzte/aktuelle Fahrplaninformationen",
        ru: "Последняя/актуальная информация о расписании",
        pt: "Últimas informações/informações atualizadas sobre o horário",
        nl: "Laatste/actuele schema-informatie",
        fr: "Dernières informations sur l'horaire actuel",
        it: "Ultime/effettive informazioni sul programma",
        es: "Información del último/actual horario",
        pl: "Informacje o ostatnim/aktualnym harmonogramie",
        uk: "Остання/фактична інформація про розклад",
        "zh-cn": "最新/实际日程信息",
    },
    "mower_raw.support_custom_pattern": {
        en: "Support custom pattern",
        de: "Unterstützung für benutzerdefinierte Muster",
        ru: "Поддержка пользовательского шаблона",
        pt: "Suporte a padrões personalizados",
        nl: "Ondersteuning voor aangepaste patronen",
        fr: "Prise en charge des motifs personnalisés",
        it: "Supporto per modelli personalizzati",
        es: "Admite patrones personalizados",
        pl: "Obsługa niestandardowego wzoru",
        uk: "Підтримка користувацького шаблону",
        "zh-cn": "支持自定义图案",
    },
    "mower_raw.mcu_ver": {
        en: "Microcontroller Unit",
        de: "Mikrocontroller-Einheit",
        ru: "Блок микроконтроллера",
        pt: "Unidade de microcontrolador",
        nl: "Microcontroller-eenheid",
        fr: "Unité de microcontrôleur",
        it: "Unità microcontrollore",
        es: "Unidad de microcontrolador",
        pl: "Jednostka mikrokontrolera",
        uk: "Блок мікроконтролера",
        "zh-cn": "微控制器单元",
    },
    "mower_raw.region": {
        en: "Current region id",
        de: "Aktuelle Regions-ID",
        ru: "Идентификатор текущего региона",
        pt: "ID da região atual",
        nl: "Huidige regio-ID",
        fr: "Identifiant de la région actuelle",
        it: "ID regione corrente",
        es: "ID de región actual",
        pl: "Aktualny identyfikator regionu",
        uk: "Поточний ідентифікатор регіону",
        "zh-cn": "当前区域 ID",
    },
    "mower_raw.pos": {
        en: "GPS module position",
        de: "GPS-Modulposition",
        ru: "положение модуля GPS",
        pt: "posição do módulo GPS",
        nl: "GPS-modulepositie",
        fr: "position du module GPS",
        it: "modulo GPS",
        es: "Posición del módulo GPS",
        pl: "Pozycja modułu GPS",
        uk: "Положення GPS-модуля",
        "zh-cn": "GPS模块位置",
    },
    "mower_raw.current_file": {
        en: "Current file infos",
        de: "Aktuelle Dateiinformationen",
        ru: "Информация о текущем файле",
        pt: "Informações do arquivo atual",
        nl: "Informatie over het huidige bestand",
        fr: "Informations sur le fichier actuel",
        it: "Informazioni sul file corrente",
        es: "Información del archivo actual",
        pl: "Aktualne informacje o pliku",
        uk: "Інформація про поточний файл",
        "zh-cn": "当前文件信息",
    },
    "mower_raw.current_work_param": {
        en: "Current work parameter",
        de: "Aktuelle Arbeitsparameter",
        ru: "Текущий рабочий параметр",
        pt: "Parâmetro de trabalho atual",
        nl: "Huidige werkparameter",
        fr: "Paramètre de travail actuel",
        it: "Parametro di lavoro attuale",
        es: "Parámetro de trabajo actual",
        pl: "Aktualny parametr pracy",
        uk: "Поточний робочий параметр",
        "zh-cn": "当前工作参数",
    },
    "mower_raw.plan_angle": {
        en: "Current cutting direction",
        de: "Aktuelle Schnittrichtung",
        ru: "Текущее направление резки",
        pt: "Direção de corte atual",
        nl: "Huidige snijrichting",
        fr: "Direction de coupe actuelle",
        it: "Direzione di taglio attuale",
        es: "Dirección de corte actual",
        pl: "Aktualny kierunek cięcia",
        uk: "Поточний напрямок різання",
        "zh-cn": "当前切割方向",
    },
    "mower_raw.path_info": {
        en: "Current path infos",
        de: "Aktuelle Pfadinformationen",
        ru: "Информация о текущем пути",
        pt: "Informações do percurso atual",
        nl: "Informatie over het huidige pad",
        fr: "Informations sur le chemin actuel",
        it: "Informazioni sul percorso corrente",
        es: "Información de ruta actual",
        pl: "Informacje o bieżącej ścieżce",
        uk: "Інформація про поточний маршрут",
        "zh-cn": "当前路径信息",
    },
};
