exports.MOWER_RAW_MQTT = {
    "mower_raw.consumable_items": {
        en: "Consumable items",
        de: "Verbrauchsmaterialien",
        ru: "Расходные материалы",
        pt: "Itens consumíveis",
        nl: "Verbruiksartikelen",
        fr: "Articles consommables",
        it: "Articoli di consumo",
        es: "Artículos consumibles",
        pl: "Przedmioty eksploatacyjne",
        uk: "Витратні матеріали",
        "zh-cn": "消耗品",
    },
    "mower_raw.blade": {
        en: "Blade info",
        de: "Klingeninformationen",
        ru: "Информация о лезвии",
        pt: "Informações sobre a lâmina",
        nl: "Informatie over het mes",
        fr: "Informations sur la lame",
        it: "Informazioni sulla lama",
        es: "Información de la hoja",
        pl: "Informacje o ostrzu",
        uk: "Інформація про лезо",
        "zh-cn": "刀片信息",
    },
    "mower_raw.charge_pos": {
        en: "Charger device position",
        de: "Position des Ladegeräts",
        ru: "Положение зарядного устройства",
        pt: "Posição do dispositivo de carregamento",
        nl: "Positie van het laadapparaat",
        fr: "position du chargeur",
        it: "Posizione del dispositivo di ricarica",
        es: "Posición del dispositivo de carga",
        pl: "Pozycja urządzenia ładującego",
        uk: "Положення зарядного пристрою",
        "zh-cn": "充电器设备位置",
    },
    "mower_raw.consumable_items.blade": {
        en: "Blade info",
        de: "Klingeninformationen",
        ru: "Информация о лезвии",
        pt: "Informações sobre a lâmina",
        nl: "Informatie over het mes",
        fr: "Informations sur la lame",
        it: "Informazioni sulla lama",
        es: "Información de la hoja",
        pl: "Informacje o ostrzu",
        uk: "Інформація про лезо",
        "zh-cn": "刀片信息",
    },
    "mower_raw.consumable_items.cutter": {
        en: "Mow cutter info",
        de: "Informationen zum Mähwerk",
        ru: "Информация о косилке",
        pt: "Informações sobre cortadores de grama",
        nl: "Informatie over grasmaaiers",
        fr: "Informations sur la tondeuse",
        it: "Informazioni sul tagliaerba",
        es: "Información sobre cortadoras de césped",
        pl: "Informacje o kosiarce",
        uk: "Інформація про косильну машину",
        "zh-cn": "割草机信息",
    },
    "mower_raw.file_17": {
        en: "Path-file uploaded",
        de: "Pfaddatei hochgeladen",
        ru: "Путь к загруженному файлу",
        pt: "Arquivo de caminho carregado",
        nl: "Padbestand geüpload",
        fr: "Fichier de chemin téléchargé",
        it: "Percorso del file caricato",
        es: "Ruta del archivo cargado",
        pl: "Plik ścieżki przesłany",
        uk: "Завантажений файл шляху",
        "zh-cn": "上传路径文件",
    },
    "mower_raw.file_7": {
        en: "Map-file uploaded",
        de: "Kartendatei hochgeladen",
        ru: "Файл карты загружен",
        pt: "Arquivo de mapa carregado",
        nl: "Kaartbestand geüpload",
        fr: "Fichier de carte téléchargé",
        it: "File della mappa caricato",
        es: "Archivo de mapa subido",
        pl: "Plik mapy przesłany",
        uk: "Завантажено файл карти",
        "zh-cn": "地图文件已上传",
    },
    "mower_raw.mow_efficiency": {
        en: "Mow efficiency",
        de: "Mähleistung",
        ru: "Эффективность кошения",
        pt: "Eficiência de corte",
        nl: "Maai-efficiëntie",
        fr: "efficacité de tonte",
        it: "Efficienza di falciatura",
        es: "eficiencia del corte",
        pl: "Efektywność koszenia",
        uk: "Ефективність скошування",
        "zh-cn": "割草效率",
    },
    "mower_raw.notice": {
        en: "Message",
        de: "Nachricht",
        ru: "Сообщение",
        pt: "Mensagem",
        nl: "Bericht",
        fr: "Message",
        it: "Messaggio",
        es: "Mensaje",
        pl: "Wiadomość",
        uk: "Повідомлення",
        "zh-cn": "信息",
    },
    "mower_raw.rain": {
        en: "Rain settings",
        de: "Regeneinstellungen",
        ru: "настройки дождя",
        pt: "Configurações de chuva",
        nl: "Regeninstellingen",
        fr: "Paramètres de pluie",
        it: "Impostazioni pioggia",
        es: "Configuración de lluvia",
        pl: "Ustawienia deszczu",
        uk: "Налаштування для дощу",
        "zh-cn": "雨景",
    },
    "mower_raw.robot_pos": {
        en: "Mower position",
        de: "Mäherposition",
        ru: "положение газонокосилки",
        pt: "Posição do cortador de grama",
        nl: "Maaipositie",
        fr: "Position de la tondeuse",
        it: "Posizione del tosaerba",
        es: "Posición de la segadora",
        pl: "Pozycja kosiarki",
        uk: "Положення косарки",
        "zh-cn": "割草机位置",
    },
    "mower_raw.rtk_pos": {
        en: "RTK position",
        de: "RTK-Position",
        ru: "Позиция RTK",
        pt: "Posição RTK",
        nl: "RTK-positie",
        fr: "Position RTK",
        it: "Posizione RTK",
        es: "Posición RTK",
        pl: "Pozycja RTK",
        uk: "Позиція RTK",
        "zh-cn": "RTK位置",
    },
    "mower_raw.schedule_info": {
        en: "Last/actual schedule infos",
        de: "Letzte/aktuelle Fahrplaninformationen",
        ru: "Последняя/актуальная информация о расписании",
        pt: "Últimas informações/informações atualizadas sobre o horário",
        nl: "Laatste/actuele schema-informatie",
        fr: "Dernières informations sur l'horaire actuel",
        it: "Ultime/effettive informazioni sul programma",
        es: "Información del último/actual horario",
        pl: "Informacje o ostatnim/aktualnym harmonogramie",
        uk: "Остання/фактична інформація про розклад",
        "zh-cn": "最新/实际日程信息",
    },
    "mower_raw.support_custom_pattern": {
        en: "Support custom pattern",
        de: "Unterstützung für benutzerdefinierte Muster",
        ru: "Поддержка пользовательского шаблона",
        pt: "Suporte a padrões personalizados",
        nl: "Ondersteuning voor aangepaste patronen",
        fr: "Prise en charge des motifs personnalisés",
        it: "Supporto per modelli personalizzati",
        es: "Admite patrones personalizados",
        pl: "Obsługa niestandardowego wzoru",
        uk: "Підтримка користувацького шаблону",
        "zh-cn": "支持自定义图案",
    },
    "mower_raw.mcu_ver": {
        en: "Microcontroller Unit",
        de: "Mikrocontroller-Einheit",
        ru: "Блок микроконтроллера",
        pt: "Unidade de microcontrolador",
        nl: "Microcontroller-eenheid",
        fr: "Unité de microcontrôleur",
        it: "Unità microcontrollore",
        es: "Unidad de microcontrolador",
        pl: "Jednostka mikrokontrolera",
        uk: "Блок мікроконтролера",
        "zh-cn": "微控制器单元",
    },
    "mower_raw.region": {
        en: "Current region id",
        de: "Aktuelle Regions-ID",
        ru: "Идентификатор текущего региона",
        pt: "ID da região atual",
        nl: "Huidige regio-ID",
        fr: "Identifiant de la région actuelle",
        it: "ID regione corrente",
        es: "ID de región actual",
        pl: "Aktualny identyfikator regionu",
        uk: "Поточний ідентифікатор регіону",
        "zh-cn": "当前区域 ID",
    },
    "mower_raw.pos": {
        en: "GPS module position",
        de: "GPS-Modulposition",
        ru: "положение модуля GPS",
        pt: "posição do módulo GPS",
        nl: "GPS-modulepositie",
        fr: "position du module GPS",
        it: "modulo GPS",
        es: "Posición del módulo GPS",
        pl: "Pozycja modułu GPS",
        uk: "Положення GPS-модуля",
        "zh-cn": "GPS模块位置",
    },
    "mower_raw.current_file": {
        en: "Current file infos",
        de: "Aktuelle Dateiinformationen",
        ru: "Информация о текущем файле",
        pt: "Informações do arquivo atual",
        nl: "Informatie over het huidige bestand",
        fr: "Informations sur le fichier actuel",
        it: "Informazioni sul file corrente",
        es: "Información del archivo actual",
        pl: "Aktualne informacje o pliku",
        uk: "Інформація про поточний файл",
        "zh-cn": "当前文件信息",
    },
    "mower_raw.current_work_param": {
        en: "Current work parameter",
        de: "Aktuelle Arbeitsparameter",
        ru: "Текущий рабочий параметр",
        pt: "Parâmetro de trabalho atual",
        nl: "Huidige werkparameter",
        fr: "Paramètre de travail actuel",
        it: "Parametro di lavoro attuale",
        es: "Parámetro de trabajo actual",
        pl: "Aktualny parametr pracy",
        uk: "Поточний робочий параметр",
        "zh-cn": "当前工作参数",
    },
    "mower_raw.plan_angle": {
        en: "Current cutting direction",
        de: "Aktuelle Schnittrichtung",
        ru: "Текущее направление резки",
        pt: "Direção de corte atual",
        nl: "Huidige snijrichting",
        fr: "Direction de coupe actuelle",
        it: "Direzione di taglio attuale",
        es: "Dirección de corte actual",
        pl: "Aktualny kierunek cięcia",
        uk: "Поточний напрямок різання",
        "zh-cn": "当前切割方向",
    },
    "mower_raw.path_info": {
        en: "Current path infos",
        de: "Aktuelle Pfadinformationen",
        ru: "Информация о текущем пути",
        pt: "Informações do percurso atual",
        nl: "Informatie over het huidige pad",
        fr: "Informations sur le chemin actuel",
        it: "Informazioni sul percorso corrente",
        es: "Información de ruta actual",
        pl: "Informacje o bieżącej ścieżce",
        uk: "Інформація про поточний маршрут",
        "zh-cn": "当前路径信息",
    },
    elec: {
        en: "Battery charger state",
        de: "Batterieladezustand",
        ru: "Состояние заряда батареи",
        pt: "Estado do carregador de bateria",
        nl: "Batterijladerstatus",
        fr: "État du chargeur de batterie",
        it: "stato del caricabatterie",
        es: "Estado del cargador de batería",
        pl: "Stan ładowarki akumulatora",
        uk: "Стан зарядного пристрою акумулятора",
        "zh-cn": "电池充电器状态",
    },
    wifi_sig: {
        en: "Wifi quality",
        de: "WLAN-Qualität",
        ru: "Качество Wi-Fi",
        pt: "Qualidade do Wi-Fi",
        nl: "Wifi-kwaliteit",
        fr: "Qualité du Wi-Fi",
        it: "Qualità Wi-Fi",
        es: "calidad del wifi",
        pl: "Jakość Wi-Fi",
        uk: "Якість Wi-Fi",
        "zh-cn": "WiFi质量",
    },
    weekly_work_area: {
        en: "Weekly work area",
        de: "Wöchentlicher Arbeitsbereich",
        ru: "Еженедельная рабочая зона",
        pt: "Área de trabalho semanal",
        nl: "Wekelijks werkgebied",
        fr: "Zone de travail hebdomadaire",
        it: "Area di lavoro settimanale",
        es: "Área de trabajo semanal",
        pl: "Tygodniowy obszar pracy",
        uk: "Тижнева робоча зона",
        "zh-cn": "每周工作区域",
    },
    weekly_work_time: {
        en: "Weekly work time",
        de: "Wöchentliche Arbeitszeit",
        ru: "Еженедельное рабочее время",
        pt: "Horário de trabalho semanal",
        nl: "Wekelijkse werktijd",
        fr: "Temps de travail hebdomadaire",
        it: "Orario di lavoro settimanale",
        es: "Tiempo de trabajo semanal",
        pl: "Tygodniowy czas pracy",
        uk: "Тижневий робочий час",
        "zh-cn": "每周工作时间",
    },
    trim_height: {
        en: "trim height",
        de: "Trimmhöhe",
        ru: "высота обрезки",
        pt: "altura de corte",
        nl: "trimhoogte",
        fr: "hauteur de garniture",
        it: "altezza di rifinitura",
        es: "altura de recorte",
        pl: "wysokość przycięcia",
        uk: "висота обрізки",
        "zh-cn": "修剪高度",
    },
    soc_temp: {
        en: "State of Charge Temperature",
        de: "Ladezustandstemperatur",
        ru: "Состояние заряда Температура",
        pt: "Temperatura do estado de carga",
        nl: "Laadstatustemperatuur",
        fr: "État de charge Température",
        it: "Stato di carica Temperatura",
        es: "Temperatura del estado de carga",
        pl: "Stan naładowania Temperatura",
        uk: "Стан заряду Температура",
        "zh-cn": "荷电状态温度",
    },
    camera_temp: {
        en: "Camera Temperature",
        de: "Kameratemperatur",
        ru: "Температура камеры",
        pt: "Temperatura da câmera",
        nl: "Cameratemperatuur",
        fr: "Température de la caméra",
        it: "Temperatura della fotocamera",
        es: "Temperatura de la cámara",
        pl: "Temperatura kamery",
        uk: "Температура камери",
        "zh-cn": "相机温度",
    },
    ip_addr: {
        en: "IP Address",
        de: "IP-Adresse",
        ru: "IP-адрес",
        pt: "Endereço IP",
        nl: "IP-adres",
        fr: "Adresse IP",
        it: "Indirizzo IP",
        es: "Dirección IP",
        pl: "Adres IP",
        uk: "IP-адреса",
        "zh-cn": "IP地址",
    },
    wifi_mac: {
        en: "Wifi MAC Address",
        de: "WLAN-MAC-Adresse",
        ru: "MAC-адрес Wi-Fi",
        pt: "Endereço MAC do Wi-Fi",
        nl: "Wifi MAC-adres",
        fr: "Adresse MAC Wi-Fi",
        it: "Indirizzo MAC Wi-Fi",
        es: "Dirección MAC de Wifi",
        pl: "Adres MAC Wi-Fi",
        uk: "MAC-адреса Wi-Fi",
        "zh-cn": "WiFi MAC 地址",
    },
    net_4g_sig: {
        en: "Network 4G signal (-120 for unavailable)",
        de: "4G-Netzwerksignal (-120 für nicht verfügbar)",
        ru: "Сигнал сети 4G (-120 означает недоступность)",
        pt: "Sinal de rede 4G (-120 para indisponível)",
        nl: "4G-netwerksignaal (-120 voor niet beschikbaar)",
        fr: "Signal réseau 4G (-120 pour indisponible)",
        it: "Segnale di rete 4G (-120 per non disponibile)",
        es: "Señal de red 4G (-120 para no disponible)",
        pl: "Sygnał sieci 4G (-120 oznacza niedostępny)",
        uk: "Сигнал мережі 4G (-120, якщо недоступний)",
        "zh-cn": "4G网络信号（-120表示不可用）",
    },
    lat: {
        en: "latitude",
        de: "Breite",
        ru: "широта",
        pt: "latitude",
        nl: "breedte",
        fr: "latitude",
        it: "latitudine",
        es: "latitud",
        pl: "szerokość",
        uk: "широта",
        "zh-cn": "纬度",
    },
    lng: {
        en: "longitude",
        de: "Länge",
        ru: "долгота",
        pt: "longitude",
        nl: "lengte",
        fr: "longitude",
        it: "longitudine",
        es: "longitud",
        pl: "długość geograficzna",
        uk: "довгота",
        "zh-cn": "经度",
    },
    firmware_version: {
        en: "Firmware Version",
        de: "Firmware-Version",
        ru: "Версия прошивки",
        pt: "Versão do firmware",
        nl: "Firmwareversie",
        fr: "Version du firmware",
        it: "Versione del firmware",
        es: "Versión del firmware",
        pl: "Wersja oprogramowania sprzętowego",
        uk: "Версія прошивки",
        "zh-cn": "固件版本",
    },
    firmwareV1Version: {
        en: "Firmware Version",
        de: "Firmware-Version",
        ru: "Версия прошивки",
        pt: "Versão do firmware",
        nl: "Firmwareversie",
        fr: "Version du firmware",
        it: "Versione del firmware",
        es: "Versión del firmware",
        pl: "Wersja oprogramowania sprzętowego",
        uk: "Версія прошивки",
        "zh-cn": "固件版本",
    },
    total_area: {
        en: "Total mown area",
        de: "Gesamte gemähte Fläche",
        ru: "Общая площадь скошенной травы",
        pt: "Área total cortada",
        nl: "Totale gemaaid oppervlak",
        fr: "Surface totale tondue",
        it: "Superficie totale falciata",
        es: "Superficie total segada",
        pl: "Całkowita powierzchnia skoszenia",
        uk: "Загальна площа скошеної землі",
        "zh-cn": "总割草面积",
    },
    total_work_count: {
        en: "Number of work assignments",
        de: "Anzahl der Arbeitsaufträge",
        ru: "Количество рабочих заданий",
        pt: "Número de tarefas de trabalho",
        nl: "Aantal werkopdrachten",
        fr: "Nombre de tâches à accomplir",
        it: "Numero di incarichi di lavoro",
        es: "Número de asignaciones de trabajo",
        pl: "Liczba zadań",
        uk: "Кількість робочих завдань",
        "zh-cn": "工作任务数量",
    },
    total_time: {
        en: "Total mowing time",
        de: "Gesamte Mähzeit",
        ru: "Общее время кошения",
        pt: "Tempo total de corte da grama",
        nl: "Totale maaitijd",
        fr: "Temps total de tonte",
        it: "Tempo totale di falciatura",
        es: "Tiempo total de corte",
        pl: "Całkowity czas koszenia",
        uk: "Загальний час скошування",
        "zh-cn": "总割草时间",
    },
    today_work_time: {
        en: "Today work time",
        de: "Arbeitszeit heute",
        ru: "Сегодняшнее рабочее время",
        pt: "Horário de trabalho de hoje",
        nl: "Vandaag werktijd",
        fr: "Aujourd'hui, temps de travail",
        it: "Oggi orario di lavoro",
        es: "Horario de trabajo de hoy",
        pl: "Dzisiejszy czas pracy",
        uk: "Сьогоднішній робочий час",
        "zh-cn": "今天工作时间",
    },
    today_fault_time: {
        en: "Today fault time",
        de: "Heute Fehlerzeit",
        ru: "Сегодняшнее время неисправности",
        pt: "Hora da falha de hoje",
        nl: "Vandaag fouttijd",
        fr: "Aujourd'hui, heure de panne",
        it: "Oggi è il momento del guasto",
        es: "Hoy es hora de fallas",
        pl: "Dzisiejszy czas awarii",
        uk: "Сьогодні час несправності",
        "zh-cn": "今天故障时间",
    },
    task_cover_area: {
        en: "Task cover area",
        de: "Aufgabenbereich",
        ru: "Область покрытия задачи",
        pt: "Área de cobertura da tarefa",
        nl: "Taakdekkingsgebied",
        fr: "Zone de couverture des tâches",
        it: "Area di copertura delle attività",
        es: "Área de cobertura de la tarea",
        pl: "Obszar objęty zadaniem",
        uk: "Зона покриття завдання",
        "zh-cn": "任务覆盖区域",
    },
    area: {
        en: "Area",
        de: "Bereich",
        ru: "Область",
        pt: "Área",
        nl: "Gebied",
        fr: "Zone",
        it: "Zona",
        es: "Área",
        pl: "Obszar",
        uk: "Площа",
        "zh-cn": "区域",
    },
    net4gSigNormal: {
        en: "Network 4G Signal Normal (-90 for unavailable)",
        de: "4G-Netzwerksignal normal (-90 für nicht verfügbar)",
        ru: "Сигнал сети 4G: нормальный (-90 при недоступности)",
        pt: "Sinal de rede 4G normal (-90 para indisponível)",
        nl: "Netwerk 4G-signaal normaal (-90 voor niet beschikbaar)",
        fr: "Signal réseau 4G normal (-90 pour indisponible)",
        it: "Segnale di rete 4G normale (-90 per non disponibile)",
        es: "Señal de red 4G normal (-90 para no disponible)",
        pl: "Sygnał sieci 4G normalny (-90 oznacza niedostępny)",
        uk: "Сигнал мережі 4G Нормальний (-90 для недоступних)",
        "zh-cn": "4G网络信号正常（-90表示不可用）",
    },
    net_4g_rsrp: {
        en: "4G Reference Signal Received Power",
        de: "Empfangsleistung des 4G-Referenzsignals",
        ru: "Мощность принимаемого опорного сигнала 4G",
        pt: "Potência do sinal de referência 4G recebido",
        nl: "4G Referentiesignaal Ontvangen Vermogen",
        fr: "Puissance reçue du signal de référence 4G",
        it: "Potenza del segnale di riferimento 4G ricevuto",
        es: "Potencia recibida de la señal de referencia 4G",
        pl: "Moc odbieranego sygnału referencyjnego 4G",
        uk: "Потужність прийманого опорного сигналу 4G",
        "zh-cn": "4G参考信号接收功率",
    },
    net_4g_rsrq: {
        en: "4G Reference Signal Received Quality",
        de: "Empfangsqualität des 4G-Referenzsignals",
        ru: "Качество принимаемого эталонного сигнала 4G",
        pt: "Qualidade do sinal de referência 4G recebido",
        nl: "Kwaliteit van het ontvangen 4G-referentiesignaal",
        fr: "Qualité du signal de référence 4G reçu",
        it: "Qualità del segnale di riferimento 4G ricevuto",
        es: "Calidad de recepción de la señal de referencia 4G",
        pl: "Jakość odbioru sygnału referencyjnego 4G",
        uk: "Якість отриманого опорного сигналу 4G",
        "zh-cn": "4G参考信号接收质量",
    },
    status: {
        en: "Device status",
        de: "Gerätestatus",
        ru: "Состояние устройства",
        pt: "Estado do dispositivo",
        nl: "Apparaatstatus",
        fr: "État de l'appareil",
        it: "stato del dispositivo",
        es: "Estado del dispositivo",
        pl: "Status urządzenia",
        uk: "Стан пристрою",
        "zh-cn": "设备状态",
    },
    event_code: {
        en: "Event code",
        de: "Ereigniscode",
        ru: "код события",
        pt: "Código do evento",
        nl: "Gebeurteniscode",
        fr: "Code d'événement",
        it: "Codice evento",
        es: "Código de evento",
        pl: "Kod zdarzenia",
        uk: "Код події",
        "zh-cn": "事件代码",
    },
    relo_status: {
        en: "Location Status",
        de: "Standortstatus",
        ru: "Статус местоположения",
        pt: "Status da localização",
        nl: "Locatiestatus",
        fr: "État de l'emplacement",
        it: "Stato della posizione",
        es: "Estado de la ubicación",
        pl: "Status lokalizacji",
        uk: "Статус місцезнаходження",
        "zh-cn": "位置状态",
    },
    algo_status: {
        en: "Algorithm Status",
        de: "Algorithmusstatus",
        ru: "Статус алгоритма",
        pt: "Status do algoritmo",
        nl: "Algoritmestatus",
        fr: "État de l'algorithme",
        it: "Stato dell'algoritmo",
        es: "Estado del algoritmo",
        pl: "Status algorytmu",
        uk: "Стан алгоритму",
        "zh-cn": "算法状态",
    },
    trim_enable: {
        en: "Trim enabled",
        de: "Trim aktiviert",
        ru: "Функция обрезки включена",
        pt: "Aparar ativado",
        nl: "Trim ingeschakeld",
        fr: "Trim activé",
        it: "Rifinitura abilitata",
        es: "Recorte habilitado",
        pl: "Przycinanie włączone",
        uk: "Обрізання ввімкнено",
        "zh-cn": "已启用修剪",
    },
    trimmerStatus: {
        en: "Trimmer Status",
        de: "Trimmerstatus",
        ru: "Состояние триммера",
        pt: "Status do aparador",
        nl: "Trimmerstatus",
        fr: "État du coupe-bordures",
        it: "Stato del trimmer",
        es: "Estado de la recortadora",
        pl: "Status trymera",
        uk: "Стан тримера",
        "zh-cn": "修剪器状态",
    },
    work_time: {
        en: "Work time",
        de: "Arbeitszeit",
        ru: "Рабочее время",
        pt: "Horário de trabalho",
        nl: "Werktijd",
        fr: "Temps de travail",
        it: "Orario di lavoro",
        es: "Horario de trabajo",
        pl: "Czas pracy",
        uk: "Робочий час",
        "zh-cn": "工作时间",
    },
    time_zone: {
        en: "Time zone",
        de: "Zeitzone",
        ru: "Часовой пояс",
        pt: "Fuso horário",
        nl: "Tijdzone",
        fr: "Fuseau horaire",
        it: "Fuso orario",
        es: "Huso horario",
        pl: "Strefa czasowa",
        uk: "Часовий пояс",
        "zh-cn": "时区",
    },
    timeZoneId: {
        en: "Time zone id",
        de: "Zeitzonen-ID",
        ru: "Идентификатор часового пояса",
        pt: "ID do fuso horário",
        nl: "Tijdzone-ID",
        fr: "Identifiant du fuseau horaire",
        it: "ID del fuso orario",
        es: "ID de zona horaria",
        pl: "Identyfikator strefy czasowej",
        uk: "Ідентифікатор часового поясу",
        "zh-cn": "时区 ID",
    },
    timeZoneCode: {
        en: "Time zone code",
        de: "Zeitzonencode",
        ru: "код часового пояса",
        pt: "Código do fuso horário",
        nl: "Tijdzonecode",
        fr: "code de fuseau horaire",
        it: "codice del fuso orario",
        es: "código de zona horaria",
        pl: "Kod strefy czasowej",
        uk: "Код часового поясу",
        "zh-cn": "时区代码",
    },
    task_total_area: {
        en: "Task total area",
        de: "Gesamtfläche der Aufgabe",
        ru: "Общая площадь задачи",
        pt: "Área total da tarefa",
        nl: "Totale oppervlakte van de taak",
        fr: "Surface totale de la tâche",
        it: "Area totale del compito",
        es: "Área total de la tarea",
        pl: "Całkowity obszar zadania",
        uk: "Загальна площа завдання",
        "zh-cn": "任务总面积",
    },
    task_id: {
        en: "Task id",
        de: "Aufgaben-ID",
        ru: "Идентификатор задачи",
        pt: "ID da tarefa",
        nl: "Taak-ID",
        fr: "ID de tâche",
        it: "ID attività",
        es: "ID de tarea",
        pl: "Identyfikator zadania",
        uk: "Ідентифікатор завдання",
        "zh-cn": "任务 ID",
    },
    all_area: {
        en: "All zone total",
        de: "Gesamtsumme aller Zonen",
        ru: "Суммарная сумма по всем зонам",
        pt: "Total de todas as zonas",
        nl: "Totaal van alle zones",
        fr: "Total de la zone",
        it: "Totale di tutte le zone",
        es: "Total de todas las zonas",
        pl: "Całkowita suma stref",
        uk: "Загальна сума за всі зони",
        "zh-cn": "所有区域总计",
    },
    all_time: {
        en: "All zone mown time total",
        de: "Gesamte Mähzeit aller Zonen",
        ru: "Общее время скашивания во всех зонах",
        pt: "Tempo total de corte em todas as zonas",
        nl: "Totale maaitijd van alle zones",
        fr: "Temps total de tonte toutes zones",
        it: "Tempo totale di falciatura di tutte le zone",
        es: "Tiempo total de corte de césped en todas las zonas",
        pl: "Całkowity czas koszenia w całej strefie",
        uk: "Загальний час скошування по всій зоні",
        "zh-cn": "所有区域割草时间总计",
    },
    auto_ride_edge_map_m: {
        en: "Automatic Edge Mapping",
        de: "Automatische Kantenerkennung",
        ru: "Автоматическое отображение границ",
        pt: "Mapeamento automático de bordas",
        nl: "Automatische randmapping",
        fr: "Cartographie automatique des bords",
        it: "Mappatura automatica dei bordi",
        es: "Mapeo automático de bordes",
        pl: "Automatyczne mapowanie krawędzi",
        uk: "Автоматичне картографування країв",
        "zh-cn": "自动边缘映射",
    },
    auto_ride_edge_map_s: {
        en: "Automatic Ride-on Edge Mapping Status",
        de: "Automatischer Status der Fahrkantenkartierung",
        ru: "Автоматическое определение состояния кромки сиденья",
        pt: "Status do mapeamento automático Ride-on Edge",
        nl: "Status van automatische kaartweergave van de Ride-on Edge",
        fr: "État de la cartographie automatique des bords de la voiture",
        it: "Stato della mappatura automatica dei bordi del veicolo",
        es: "Estado de mapeo automático de bordes durante el recorrido",
        pl: "Status automatycznego mapowania krawędzi jazdy",
        uk: "Стан автоматичного картографування країв під час їзди",
        "zh-cn": "自动行驶边缘映射状态",
    },
    dev_model: {
        en: "Device Model",
        de: "Gerätemodell",
        ru: "Модель устройства",
        pt: "Modelo do dispositivo",
        nl: "Apparaatmodel",
        fr: "Modèle d'appareil",
        it: "Modello del dispositivo",
        es: "Modelo de dispositivo",
        pl: "Model urządzenia",
        uk: "Модель пристрою",
        "zh-cn": "设备型号",
    },
    dev_name: {
        en: "Device Name",
        de: "Gerätename",
        ru: "Название устройства",
        pt: "Nome do dispositivo",
        nl: "Apparaatnaam",
        fr: "Nom de l'appareil",
        it: "Nome del dispositivo",
        es: "Nombre del dispositivo",
        pl: "Nazwa urządzenia",
        uk: "Назва пристрою",
        "zh-cn": "设备名称",
    },
};
exports.MOWER_RAW_MQTT_UNITS = {
    elec: "%",
    wifi_sig: "dBm",
    weekly_work_area: "m²",
    task_total_area: "m²",
    all_area: "m²",
    weekly_work_time: "min",
    all_time: "min",
    time_zone: "sec",
    work_time: "min",
    trim_height: "cm",
    soc_temp: "°C",
    camera_temp: "°C",
    net_4g_sig: "dBm",
    total_area: "m²",
    total_time: "min",
    today_work_time: "min",
    today_fault_time: "min",
    task_cover_area: "m²",
    area: "m²",
    net4gSigNormal: "dBm",
    net_4g_rsrp: "dBm",
    net_4g_rsrq: "dBm",
};
exports.MOWER_RAW_MQTT_ROLES = {
    lat: "value.gps.latitude",
    lng: "value.gps.longitude",
    picUrl: "text.url",
    url: "text.url",
    region_id: "value",
    elec: "value.battery",
    wifi_sig: "value.rssi",
    soc_temp: "value.temperature",
    camera_temp: "value.temperature",
    ip_addr: "info.ip",
    wifi_mac: "info.mac",
    net_4g_sig: "value.rssi",
    firmware_version: "info.firmware",
    firmwareV1Version: "info.firmware",
    map_url: "text.url",
    picUrlDetail: "text.url",
    net4gSigNormal: "value.rssi",
    net_4g_rsrp: "value.rssi",
    net_4g_rsrq: "value.rssi",
};
